CREATE TABLE USER_ACCOUNT(
  ID		INT AUTO_INCREMENT PRIMARY KEY,
  NAME		VARCHAR(255),
  LOGIN		VARCHAR(255) CONSTRAINT UNQ_USER_LOGIN UNIQUE (LOGIN),
  PASSWORD	VARCHAR(32),
  SALT		VARCHAR(32)
);

CREATE TABLE PERMISSIONS(
  ID		INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID	INT CONSTRAINT FK_AUTHORITY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (ID),
  ROLE		VARCHAR(255),
  SITE		VARCHAR(255)
);

CREATE TABLE ACTIVITY(
  ID			INT AUTO_INCREMENT PRIMARY KEY,
  AUTHORITY_ID	INT CONSTRAINT FK_ACTIVITY_AUTHORITY_ID FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY (ID),
  LOGIN_DATE	DATE,
  LOGOUT_DATE	DATE,
  VOLUME		INT
);

CREATE INDEX IDX_AUTHORITY
  ON AUTHORITY (USER_ID, ROLE);